default: &default
  adapter:    postgresql
  encoding:   unicode
  pool:       <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port:       <%= ENV.fetch("RABBITMQ_DB_PORT") %>
  host:       <%= ENV.fetch("RABBITMQ_DB_HOST") %>
  username:   <%= ENV.fetch("RABBITMQ_DB_USERNAME") %>
  password:   <%= ENV.fetch("RABBITMQ_DB_PASSWORD") %>

development:
  <<: *default
  database: Warehouse_development

test:
  <<: *default
  database: Warehouse_test

production:
  <<: *default
  database: Warehouse_production
